server:
  port: 9009
  servlet:
    context-path: /sms

spring:
  application:
    name: flashj-sms

  main:
    allow-bean-definition-overriding: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.87.141
    port: 6379
    shutdown-timeout: 100
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 10000
    timeout: 10000

sms:
  qcloud:
    appId: 1400336270
    appKey: 86f89b807815b2d64196e31a14bb1806
    templateId: 234323
    sign: 签名

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml



